"use client";

import React from "react";
import { useState } from "react";
import "@components/Report-temp/report-temp.scss";
import ReportTable from './function';

export default function Page() {
    const data = [
        { number: '1', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'%', 
        indicatorsName:'ความคืบหน้าการดำเนินงาน', note:''},
        { number: '2', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน-ครั้ง', 
        indicatorsName:'จำนวนการรับรู้สื่อ', note:'เพิ่ม ปี 67'},
        { number: '3', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'PAX', 
        indicatorsName:'จำนวนผู้ซื้อสินค้า/บริการท่องเที่ยว', note:''},
        { number: '4', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'Content', 
        indicatorsName:'จำนวน Content', note:''},
        { number: '5', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการเข้าร่วมประชุม/ให้คำแนะนำปรึกษาเพื่อส่งเสริมศักยภาพด้านการตลาดการท่องเที่ยวแก่หน่วยงานภายนอก', note:''},
        { number: '6', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการจัด Agent FAM Trip', note:''},
        { number: '7', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการจัด Media FAM Trip', note:''},
        { number: '8', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'งาน', 
        indicatorsName:'จำนวนการจัด/เข้าร่วมงานส่งเสริมการขาย', note:''},
        { number: '9', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการจัดกิจกรรม Online', note:''},
        { number: '10', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนการจัดกิจกรรม Product Testing', note:''},
        { number: '11', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการจัดกิจกรรมอื่นๆ', note:''},
        { number: '12', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการจัดคาราวาน/แรลลี่', note:''},
        { number: '13', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการจัดงานแถลงข่าว', note:''},
        { number: '14', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการจัดประชุม', note:''},
        { number: '15', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'รายการ', 
        indicatorsName:'จำนวนการทำข้อตกลงทางธุรกิจในกิจกรรมส่งเสริมการขาย', note:''},
        { number: '16', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'รายการ', 
        indicatorsName:'จำนวนการทำสัญญา/ข้อตกลงทางธุรกิจในกิจกรรมส่งเสริมการขาย', note:''},
        { number: '17', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการบอกต่อ', note:''},
        { number: '18', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน-ครั้ง', 
        indicatorsName:'จำนวนการบอกต่อ (Like Share Comment)', note:''},
        { number: '19', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการสำรวจข้อมูลเสียงของลูกค้า /ผู้มีส่วนได้ส่วนเสีย (VOC/VOS)', note:''},
        { number: '20', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการสำรวจเพื่อประเมินศักยภาพสินค้าการท่องเทียว', note:''},
        { number: '21', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนการสำรวจเส้นทาง', note:''},
        { number: '22', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'งาน', 
        indicatorsName:'จำนวนกิจกรรม เทศกาล ประเพณี ที่ ททท. จัด', note:''},
        { number: '23', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'งาน', 
        indicatorsName:'จำนวนกิจกรรม เทศกาล ประเพณี ที่ ททท. สนับสนุน', note:''},
        { number: '24', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรมรับฟังเสียงของลูกค้า', note:''},
        { number: '25', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรมสร้าง/รักษาความสัมพันธ์เครือข่าย', note:''},
        { number: '26', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรมสร้างความเข้าใจให้หน่วยงานที่เกี่ยวข้อง', note:''},
        { number: '27', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรมเสริมศักยภาพให้หน่วยงานที่เกี่ยวข้อง', note:''},
        { number: '28', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'หน่วย', 
        indicatorsName:'จำนวนข้อมูลนำเข้า', note:''},
        { number: '29', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนครั้งการเสนอขายสินค้า/บริการท่องเที่ยวร่วมกับพันธมิตร (Joint Promotion)', note:''},
        { number: '30', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนครั้งที่ประสานงานกับหน่วยงานภายใน ททท.', note:''},
        { number: '31', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ครั้ง',
        indicatorsName:'จำนวนความถี่ในการเผยแพร่โฆษณา/ประชาสัมพันธ์แยกตามประเภทสื่อ', note:''},
        { number: '32', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'โครงการ', 
        indicatorsName:'จำนวนโครงการต้นแบบ', note:''},
        { number: '33', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ชิ้นงาน', 
        indicatorsName:'จำนวนงานวิจัย/ ผลการศึกษา', note:''},
        { number: '34', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ช่องทาง', 
        indicatorsName:'จำนวนช่องทางในการเผยแพร่โฆษณา/ประชาสัมพันธ์แยกตามประเภทสื่อ', note:''},
        { number: '35', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ชิ้น', 
        indicatorsName:'จำนวนชิ้นงานโฆษณา/ประชาสัมพันธ์แยกตามประเภทสื่อ', note:''},
        { number: '36', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ชิ้น', 
        indicatorsName:'จำนวนชิ้นงานโฆษณาแยกตามประเภทสื่อ', note:''},
        { number: '37', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ชิ้น', 
        indicatorsName:'จำนวนชิ้นงานประชาสัมพันธ์แยกตามประเภทสื่อ', note:'เพิ่มปี 67'},
        { number: '38', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'หน่วยงาน', 
        indicatorsName:'จำนวนชุมชน/ผู้ประกอบการ ที่ได้รับการสร้างสรรค์/พัฒนาสินค้าและบริการ ตามแนวทางที่ ททท. กำหนด', note:''},
        { number: '39', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ราย/ชุมชน', 
        indicatorsName:'จำนวนชุมชนท่องเที่ยวที่เข้าร่วมกิจกรรม', note:''},
        { number: '40', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ธุรกิจ', 
        indicatorsName:'จำนวนธุรกิจท่องเที่ยวที่เกิดจากการดำเนินงานของ ททท. ร่วมกับหน่วยงานภาครัฐ/เอกชน/เครือข่ายสร้างสรรค์', note:''},
        { number: '41', planName: 'ตลาดในประเทศ', type:'รายงานผลจากรวมผลรายละเอียดย่อย', calculating:'ผลรวมจำนวน', measure:'ชิ้นงาน', 
        indicatorsName:'จำนวนนวัตกรรมการท่องเที่ยวที่เกิดจากการดำเนินงานของ ททท.', note:''},
        { number: '42', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'บทความ/ข่าว', 
        indicatorsName:'จำนวนบทความ/ข่าว ที่ได้รับการเผยแพร่', note:''},
        { number: '43', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'หน่วยงาน', 
        indicatorsName:'จำนวนบริษัทนำเที่ยวที่นำสินค้า/บริการไปเสนอขายต่อ', note:''},
        { number: '44', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน', 
        indicatorsName:'จำนวนผู้ขอรับข้อมูลข่าวสารทางการท่องเที่ยวจาก ททท.', note:''},
        { number: '45', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'หน่วยงาน', 
        indicatorsName:'จำนวนผู้ขาย(seller) ที่เข้าร่วมงาน', note:''},
        { number: '46', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน', 
        indicatorsName:'จำนวนผู้เข้าชมงาน', note:''},
        { number: '47', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน', 
        indicatorsName:'จำนวนผู้เข้าร่วมกิจกรรม Online', note:''},
        { number: '48', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน', 
        indicatorsName:'จำนวนผู้เข้าร่วมกิจกรรมในโครงการ (คนนอกพื้นที่)', note:''},
        { number: '49', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน', 
        indicatorsName:'จำนวนผู้เข้าร่วมกิจกรรมในโครงการ (คนในพื้นที่)', note:''},

        { number: '50', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'หน่วยงาน', 
        indicatorsName:'จำนวนผู้ซื้อ(buyer) ที่เข้าร่วมงาน', note:''},
        { number: '51', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'หน่วยงาน', 
        indicatorsName:'จำนวนผู้ประกอบการที่เข้าร่วมกิจกรรม', note:''},
        { number: '52', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน', 
        indicatorsName:'จำนวนผู้รับจ้างเหมาบริการ', note:''},
        { number: '53', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'แผน/แนวทาง', 
        indicatorsName:'จำนวนแผน/แนวทางการดำเนินโครงการ', note:''},
        { number: '54', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'หน่วยงาน', 
        indicatorsName:'จำนวนพันธมิตรร่วมจัด/สนับสนุนค่าใช้จ่าย', note:''},
    ];
    
    return (
        <>
            <div className='d-flex flex-column' style={{width: '100%'}}>
                <div className='search-wrapper-section d-flex flex-column'>
                    <div className="master-data2 d-flex flex-row p-2 justify-content-center">
                        <ReportTable data={data}/>
                    </div>
                </div>
            </div>
        </>
    )
}