import { FormState, ISearchDataObj } from "./types";

export const installment = {
  installment_1: false,
  installment_2: false,
  installment_3: false,
  installment_4: false,
  installment_5: false,
  installment_6: false,
  installment_7: false,
  installment_8: false,
  installment_9: false,
  installment_10: false,
  installment_11: false,
  installment_12: false,
  installment_13: false,
  installment_14: false,
  installment_15: false,
  installment_16: false,
  installment_17: false,
  installment_18: false,
  installment_19: false,
  installment_20: false,
  installment_21: false,
  installment_22: false,
  installment_23: false,
  installment_24: false,
};

export const ISMAmount = {
  ism_amount_1: "",
  ism_amount_2: "",
  ism_amount_3: "",
  ism_amount_4: "",
  ism_amount_5: "",
  ism_amount_6: "",
  ism_amount_7: "",
  ism_amount_8: "",
  ism_amount_9: "",
  ism_amount_10: "",
  ism_amount_11: "",
  ism_amount_12: "",
  ism_amount_13: "",
  ism_amount_14: "",
  ism_amount_15: "",
  ism_amount_16: "",
  ism_amount_17: "",
  ism_amount_18: "",
  ism_amount_19: "",
  ism_amount_20: "",
  ism_amount_21: "",
  ism_amount_22: "",
  ism_amount_23: "",
  ism_amount_24: "",
};

export const ISMQuarter = {
  ism_quarter_1: "",
  ism_quarter_2: "",
  ism_quarter_3: "",
  ism_quarter_4: "",
  ism_quarter_5: "",
  ism_quarter_6: "",
  ism_quarter_7: "",
  ism_quarter_8: "",
  ism_quarter_9: "",
  ism_quarter_10: "",
  ism_quarter_11: "",
  ism_quarter_12: "",
  ism_quarter_13: "",
  ism_quarter_14: "",
  ism_quarter_15: "",
  ism_quarter_16: "",
  ism_quarter_17: "",
  ism_quarter_18: "",
  ism_quarter_19: "",
  ism_quarter_20: "",
  ism_quarter_21: "",
  ism_quarter_22: "",
  ism_quarter_23: "",
  ism_quarter_24: "",
};

export const ISMStatus = {
  ism_status_1: null,
  ism_status_2: null,
  ism_status_3: null,
  ism_status_4: null,
  ism_status_5: null,
  ism_status_6: null,
  ism_status_7: null,
  ism_status_8: null,
  ism_status_9: null,
  ism_status_10: null,
  ism_status_11: null,
  ism_status_12: null,
  ism_status_13: null,
  ism_status_14: null,
  ism_status_15: null,
  ism_status_16: null,
  ism_status_17: null,
  ism_status_18: null,
  ism_status_19: null,
  ism_status_20: null,
  ism_status_21: null,
  ism_status_22: null,
  ism_status_23: null,
  ism_status_24: null,
};

export const initialState: FormState = {
  section: 1,
  subSection3: 1,
  obj: {
    id: "",
    fiscal_year: "",
    // project_name: "",
    type_of_statement: "",
    procurement_name: "",
    other_budget: "",
    other_budget_name: "",
    budget: "",
    purchasing_hiring_list: "",
    resp_department: "",
    resp_section: "",
    resp_unit: "",
    nature_of_work: "",
    number_of_years: "",
    continuous_work: [],
    person_in_charge_project: "",
    tel: "",
    add_action_plan: [],

    add_manually: { event_name: "", procurement_list: "", budget_limit: "" },
    amount_change: false,
    // section2
    action_plan_table: [
      // {
      //   id: "1",
      //   topic: 1,
      //   startDate: "2022-08-10",
      //   endDate: "2022-09-10",
      // },
      // {
      //   id: "2",
      //   topic: 1,
      //   startDate: "2022-08-15",
      //   endDate: "2022-11-30",
      // },
    ],
    ap1_start_date: "",
    ap1_end_date: "",
    ap2_start_date: "",
    ap2_end_date: "",
    ap3_start_date: "",
    ap3_end_date: "",
    ap4_start_date: "",
    ap4_end_date: "",
    ap5_start_date: "",
    ap5_end_date: "",
    ap6_start_date: "",
    ap6_end_date: "",
    // section 3
    quarter: "",
    result: "",
    attachment: undefined,
    note: "",
    draft_start_date: "",
    draft_end_date: "",
    follow_plan: "",
    approve_report_start_date: "",
    approve_report_end_date: "",
    proc_approve_start_date: "",
    proc_approve_end_date: "",
    proc_method: {
      // การจัดซื้อ/จัดจ้าง group id = "proc"
      proc_e_mkt: false,
      proc_e_bid: false,
      proc_announce: false,
      proc_select: false,
      proc_specific: false,
      // การเช่า group id = "rental"
      rental_select: false,
      rental_specific: false,
      // งานจ้างที่ปรึกษา group id = "hire_cst"
      hire_cst_announce: false,
      hire_cst_select: false,
      hire_cst_specific: false,
      // งานจ้างออกแบบหรือควบคุมงานก่อนสร้าง group id = "hire_design"
      hire_design_announce: false,
      hire_design_select: false,
      hire_design_specific: false,
      hire_design_contest: false,

      proc_main_method: "",
      proc_sub_method: "",
      proc_announce_method: "",
    },

    // 4. ทำสัญญาจัดซื้อ/จัดจ้าง
    contract_start_date: "",
    contract_end_date: "",
    contract_name: "",
    contract_status: "",
    contract_number: "",
    contract_date: "",
    contract_budget: "",
    contract_term_delivery: "",
    contract_remain_budget: "",
    term_of_pay_no: "24",

    // 5
    deliver_start_date: "",
    deliver_end_date: "",
    deliver_period: "",
    deliver_amount_withdrawn_before: "",
    deliver_total_amount_disbursed: "",
    deliver_balance: "",

    ...installment,
    ...ISMAmount,
    ...ISMQuarter,
    ...ISMStatus,

    // 6
    schedule_complete: "",
    final_note: "",
    commander: "",
    define_department_name: "",
  },
  search_data: [],
  search_data_count: 0,
  search_data_current_page: 1,
  search_conditions: {
    fiscal_year: "",
    resp_agency_name: "",
    indicators_name: "",
    indicators_number: 0,
    budget_investment: false,
    budget_investment_budget: false,
    budget_reserve_urgent: false,
    budget_support: false,
    budget_income: false,
    budget_other: false,
    budget_other_central: false,
    budget_other_loan: false,
    budget_other_other: false,
    proc_method: "",
    proj_activ: "",
    job_status: "",
  },
};
