import { FormState, ISearchDataObj } from "./types";

export const installment = {
  installment_1: false,
  installment_2: false,
  installment_3: false,
  installment_4: false,
  installment_5: false,
  installment_6: false,
  installment_7: false,
  installment_8: false,
  installment_9: false,
  installment_10: false,
  installment_11: false,
  installment_12: false,
};

export const ISMAmount = {
  ism_amount_1: "",
  ism_amount_2: "",
  ism_amount_3: "",
  ism_amount_4: "",
  ism_amount_5: "",
  ism_amount_6: "",
  ism_amount_7: "",
  ism_amount_8: "",
  ism_amount_9: "",
  ism_amount_10: "",
  ism_amount_11: "",
  ism_amount_12: "",
};

export const ISMQuarter = {
  ism_1_quarter: "",
  ism_2_quarter: "",
  ism_3_quarter: "",
  ism_4_quarter: "",
  ism_5_quarter: "",
  ism_6_quarter: "",
  ism_7_quarter: "",
  ism_8_quarter: "",
  ism_9_quarter: "",
  ism_10_quarter: "",
  ism_11_quarter: "",
  ism_12_quarter: "",
};

export const ISMStatus = {
  ism_status_1: true,
  ism_status_2: true,
  ism_status_3: null,
  ism_status_4: null,
  ism_status_5: null,
  ism_status_6: null,
  ism_status_7: null,
  ism_status_8: null,
  ism_status_9: null,
  ism_status_10: null,
  ism_status_11: null,
  ism_status_12: null,
};

export const initialState: FormState = {
  section: 1,
  subSection3: 1,
  obj: {
    id: "",
    fiscal_year: "",
    type_of_statement: "",
    other_budget: "",
    purchasing_hiring_list: "",
    resp_department: "",
    nature_of_work: "",
    number_of_years: "",
    department: "",
    person_in_charge_project: "",
    tel: "",
    add_manually: { event_name: "", procurement_list: "", budget_limit: "" },

    // section2
    action_plan_table: [
      // {
      //   id: "1",
      //   topic: 1,
      //   startDate: "2022-08-10",
      //   endDate: "2022-09-10",
      // },
      // {
      //   id: "2",
      //   topic: 1,
      //   startDate: "2022-08-15",
      //   endDate: "2022-11-30",
      // },
    ],
    ap1_start_date: "",
    ap1_end_date: "",
    ap2_start_date: "",
    ap2_end_date: "",
    ap3_start_date: "",
    ap3_end_date: "",
    ap4_start_date: "",
    ap4_end_date: "",
    ap5_start_date: "",
    ap5_end_date: "",
    ap6_start_date: "",
    ap6_end_date: "",
    // section 3
    quarter: "",
    result: "",
    attachment: undefined,
    note: "",
    draft_start_date: "",
    draft_end_date: "",
    follow_plan: "",
    approve_report_start_date: "",
    approve_report_end_date: "",
    proc_approve_start_date: "",
    proc_approve_end_date: "",
    proc_method: {
      // การจัดซื้อ/จัดจ้าง group id = "proc"
      proc_e_mkt: false,
      proc_e_bid: false,
      proc_announce: false,
      proc_select: false,
      proc_specific: false,
      // การเช่า group id = "rental"
      rental_select: false,
      rental_specific: false,
      // งานจ้างที่ปรึกษา group id = "hire_cst"
      hire_cst_announce: false,
      hire_cst_select: false,
      hire_cst_specific: false,
      // งานจ้างออกแบบหรือควบคุมงานก่อนสร้าง group id = "hire_design"
      hire_design_announce: false,
      hire_design_select: false,
      hire_design_specific: false,
      hire_design_contest: false,
    },

    // 4. ทำสัญญาจัดซื้อ/จัดจ้าง
    contract_start_date: "",
    contract_end_date: "",
    contract_name: "",
    contract_status: "",
    contract_number: "",
    contract_s_date: "",
    contract_e_date: "",
    contract_budget: "",
    contract_term_delivery: "",
    contract_remain_budget: "",

    // 5
    deliver_start_date: "",
    deliver_end_date: "",
    deliver_note: "",
    deliver_period: "",
    deliver_amount_withdrawn_before: "",
    deliver_total_amount_disbursed: "",
    deliver_balance: "",

    ...installment,
    ...ISMAmount,
    ...ISMQuarter,
    ...ISMStatus,

    // 6
    schedule_complete: "",
    commander: "",
    define_department_name: "",
  },
  search_data: [
    {
      id: "1",
      job_status: "เสนอผู้บังคับบัญชาเห็นชอบแผน",
      type_of_statement: "งบอุดหนุน",
      fiscal_year: "2566",
      proc_list: "",
      budget: "",
      activity: false,
      start_date: "",
      end_date: "",
      proc_method: "",
      note: "",
      resp_agency: "",
    },
    {
      id: "2",
      job_status: "เสนอผู้บังคับบัญชาเห็นชอบแผน",
      type_of_statement: "งบอุดหนุน",
      fiscal_year: "2566",
      proc_list: "",
      budget: "",
      activity: false,
      start_date: "",
      end_date: "",
      proc_method: "",
      note: "",
      resp_agency: "",
    },
  ],
};
