"use client";

import React from "react";
import { useState } from "react";
import "@components/Report-temp/report-temp.scss";
import ReportTable from './function';

export default function Page() {
    const data = [
        { number: '1', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A1 : Aware) อัตราการรับรู้ Content หลักของภูมิภาคจากการเข้าร่วมงาน', indicatorsYear:'กลยุทธ์ 1'},
        { number: '2', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A1 : Aware) อัตราการรับรู้อัตลักษณ์พื้นที่รองที่ ททท. นำเสนอ', indicatorsYear:''},
        { number: '3', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A1 : Aware) อัตราการรับรู้อัตลักษณ์เมืองรองจากการเข้าร่วมงาน', indicatorsYear:'กลยุทธ์ 1'},
        { number: '4', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A1 : Aware) อัตราการรับรู้ภาพลักษณ์องค์กรในฐานะหน่วยงานที่มีความรับผิดชอบต่อสังคมและสิ่งแวดล้อม (วัดผู้มีส่วนได้ส่วนเสีย)', indicatorsYear:''},
        { number: '5', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A2 : Appeal) อัตราความต้องการเดินทางท่องเที่ยวของคนไทย', indicatorsYear:''},
        { number: '6', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A2 : Appeal) อัตราความต้องการเดินทางท่องเที่ยวของคนไทยเพื่อสัมผัสคุณค่าแบรนด์ประเทศไทยที่ ททท. กำหนด', indicatorsYear:''},
        { number: '7', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A2 : Appeal) อัตราความต้องการเดินทางบ่อยครั้งขึ้นจากการรับข้อมูลข่าวสารจาก ททท.', indicatorsYear:''},
        { number: '8', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A2 : Appeal) อัตราความต้องการเดินทางสัมผัสอัตลักษณ์พื้นที่รองตามที่ ททท. นำเสนอ', indicatorsYear:''},
        { number: '9', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A2 : Appeal) อัตราความต้องการมีส่วนร่วมของนักท่องเที่ยวในการท่องเที่ยวอย่างรับผิดชอบต่อสังคมและสิ่งแวดล้อมจากการรับรู้สื่อของ ททท.', indicatorsYear:''},
        { number: '10', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'(A4 : Act) จำนวนความถี่ที่ต้องการเดินทางกลับมายังภูมิภาคเพิ่มขึ้นจากกิจกรรมการตลาดตามทิศทางภูมิภาค', indicatorsYear:''},
        { number: '11', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'(A4 : Act) จำนวนความถี่ที่ต้องการเดินทางเพิ่มขึ้นจากกิจกรรม (Event) ที่ ททท. จัด', indicatorsYear:''},
        { number: '12', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'วัน', 
        indicatorsName:'(A4 : Act) ระยะเวลาที่ต้องการใช้ในการท่องเที่ยวที่เพิ่มขึ้นจากกิจกรรมการตลาดตามทิศทางภูมิภาค', indicatorsYear:'กลยุทธ์ 2'},
        { number: '13', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'บาท', 
        indicatorsName:'(A4 : Act) มูลค่าการใช้จ่ายเพื่อการท่องเที่ยวอย่างสร้างสรรค์ที่ ททท. นำเสนอ', indicatorsYear:''},
        { number: '14', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'บาท', 
        indicatorsName:'(A4 : Act) มูลค่าการใช้จ่ายเพื่อซื้อสินค้ามูลค่าสูงและสินค้าวิถีไทยมูลค่าเพิ่มจากกิจกรรมการตลาดตามทิศทางภูมิภาค', indicatorsYear:''},
        { number: '15', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจในประสบการณ์ท่องเที่ยวตามทิศทางภูมิภาคที่ทำให้ความถี่เพิ่มขึ้น', indicatorsYear:''},
        { number: '16', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจในประสบการณ์เดินทางสัมผัสอัตลักษณ์เมืองรองที่ ททท. นำเสนอ', indicatorsYear:''},
        { number: '17', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจในประสบการณ์เดินทางสัมผัสอัตลักษณ์เมืองรองจากการเข้าร่วมงาน', indicatorsYear:'กลยุทธ์ 1'},
        { number: '18', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจในประสบการณ์เดินทางสัมผัสคุณค่าวันธรรมดา', indicatorsYear:''},
        { number: '19', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจของนักท่องเที่ยวชาวต่างประเทศในพื้นที่เป้าหมายต่อการให้ข้อมูล/การอำนวยความสะดวก/กิจกรรมการตลาดของ ททท. ที่มีส่วนทำให้ตัดสินใจเดินทางไปยังเมืองรอง/พื้นที่รองในเมืองหลัก', indicatorsYear:''},
        { number: '20', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจในประสบการณ์ท่องเที่ยวตามทิศทางภูมิภาคที่ทำให้ต้องใช้ระยะเวลาท่องเที่ยวนานขึ้น', indicatorsYear:'กลยุทธ์ 2'},
        { number: '21', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจในประสบการณ์ท่องเที่ยวอย่างสร้างสรรค์ที่ ททท. นำเสนอ', indicatorsYear:''},
        { number: '22', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจในประสบการณ์ท่องเที่ยวตามทิศทางภูมิภาคที่ทำให้ใช้จ่ายเพิ่มขึ้น', indicatorsYear:'กลยุทธ์ 2'},
        { number: '23', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราความพึงพอใจในประสบการณ์ท่องเที่ยวตามทิศทางภูมิภาคที่ได้มีส่วนช่วยลดผลกระทบต่อสังคมและสิ่งแวดล้อม', indicatorsYear:''},
        { number: '24', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A4 : Act) อัตราการยอมรับของกลุ่มเป้าหมายว่าสินค้าวิถีไทยที่ผ่านการพัฒนา/สร้างสรรค์มูลค่าเพิ่มของ ททท. เป็นปัจจัยที่ทำให้ตัดสินใจออกเดินทางท่องเที่ยว', indicatorsYear:''},
        { number: '25', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A5 : Advocate) อัตราการบอกต่อประสบการณ์ท่องเที่ยวตามทิศทางภูมิภาคที่ทำให้ความถี่เพิ่มขึ้น', indicatorsYear:''},
        { number: '26', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A5 : Advocate) อัตราการบอกต่อประสบการณ์เดินทางสัมผัสอัตลักษณ์เมืองรองที่ ททท. นำเสนอ', indicatorsYear:''},
        { number: '27', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A5 : Advocate) อัตราการบอกต่อประสบการณ์เดินทางสัมผัสคุณค่าวันธรรมดา', indicatorsYear:''},
        { number: '28', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A5 : Advocate) อัตราการบอกต่อประสบการณ์ท่องเที่ยวตามทิศทางภูมิภาคที่ทำให้ต้องใช้ระยะเวลาท่องเที่ยวนานขึ้น', indicatorsYear:'กลยุทธ์ 2'},
        { number: '29', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A5 : Advocate) อัตราการบอกต่อประสบการณ์ท่องเที่ยวตามทิศทางภูมิภาคที่ทำให้ใช้จ่ายเพิ่มขึ้น', indicatorsYear:'กลยุทธ์ 2'},
        { number: '30', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A5 : Advocate) อัตราการบอกต่อประสบการณ์ท่องเที่ยวอย่างสร้างสรรค์ที่ ททท. นำเสนอ', indicatorsYear:''},
        { number: '31', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ตามสัดส่วนจำนวน', measure:'%', 
        indicatorsName:'(A5 : Advocate) อัตราการบอกต่อประสบการณ์ท่องเที่ยวตามทิศทางภูมิภาคที่ได้มีส่วนช่วยลดผลกระทบต่อสังคมและสิ่งแวดล้อม', indicatorsYear:''},
        { number: '32', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน-ครั้ง', 
        indicatorsName:'จำนวนการรับรู้สื่อ', indicatorsYear:'กลยุทธ์ 1-4'},
        { number: '33', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'PAX', 
        indicatorsName:'จำนวนผู้ซื้อสินค้า/บริการท่องเที่ยว', indicatorsYear:'กลยุทธ์ 1-4'},
        { number: '34', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน', 
        indicatorsName:'จำนวนผู้เข้าร่วมกิจกรรมในโครงการ (คนนอกพื้นที่)', indicatorsYear:'กลยุทธ์ 1-4'},
        { number: '35', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'คน', 
        indicatorsName:'จำนวนผู้เข้าร่วมกิจกรรมในโครงการ (คนในพื้นที่)', indicatorsYear:'กลยุทธ์ 1-4'},
        { number: '36', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ครั้ง', 
        indicatorsName:'จำนวนครั้งที่ประสานงานกับหน่วยงาน ททท.', indicatorsYear:''},
        { number: '37', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'Event', 
        indicatorsName:'จำนวน Event เมืองรองที่พัฒนาขึ้นใหม่ตาม Content หลักของภูมิภาค', indicatorsYear:''},
        { number: '38', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) ที่พัฒนาขึ้นอย่างสอดคล้องกับทิศทางภูมิภาคในพื้นที่เมืองหลัก', indicatorsYear:'กลยุทธ์ 1'},
        { number: '39', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) ที่พัฒนาขึ้นอย่างสอดคล้องกับทิศทางภูมิภาคในพื้นที่เมืองรอง', indicatorsYear:'กลยุทธ์ 1'},
        { number: '40', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) ที่พัฒนาขึ้นอย่างสอดคล้องกับทิศทางและ Content หลักของภูมิภาคเพื่อกระตุ้นความต้องการเดินทางบ่อยครั้งขึ้นของนักท่องเที่ยวชาวไทย', indicatorsYear:''},
        { number: '41', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) ที่พัฒนาขึ้นอย่างสอดคล้องกับทิศทางและ Content หลักของภูมิภาคเพื่อกระตุ้นความถี่ในการเดินทางของนักท่องเที่ยวชาวไทย', indicatorsYear:''},
        { number: '42', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) ที่สร้างสรรค์ขึ้นใหม่อย่างสอดคล้องกับทิศทางภูมิภาคในพื้นที่เมืองหลัก', indicatorsYear:'กลยุทธ์ 1'},
        { number: '43', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) ที่สร้างสรรค์ขึ้นใหม่อย่างสอดคล้องกับทิศทางภูมิภาคในพื้นที่เมืองรอง', indicatorsYear:'กลยุทธ์ 1'},
        { number: '44', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) เมืองรองที่พัฒนาขึ้นใหม่ตาม Content หลักของภูมิภาค', indicatorsYear:''},
        { number: '45', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) ใหม่ที่สร้างสรรค์ขึ้นอย่างสอดคล้องกับทิศทางและ Content หลักของภูมิภาคเพื่อกระตุ้นความต้องการเดินทางบ่อยครั้งขึ้นของนักท่องเที่ยวชาวไทย', indicatorsYear:''},
        { number: '46', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'กิจกรรม', 
        indicatorsName:'จำนวนกิจกรรม (Event) ใหม่ที่สร้างสรรค์ขึ้นอย่างสอดคล้องกับทิศทางและ Content หลักของภูมิภาคเพื่อกระตุ้นความถี่ในการเดินทางของนักท่องเที่ยวชาวไทย', indicatorsYear:''},
        { number: '47', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'โครงการ/กิจกรรม', 
        indicatorsName:'จำนวนโครงการ/กิจกรรมที่ประสานความร่วมมือกับผู้มีส่วนได้ส่วนเสียในพื้นที่', indicatorsYear:'กลยุทธ์ 4'},
        { number: '48', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'โครงการ/กิจกรรม', 
        indicatorsName:'จำนวนโครงการ/กิจกรรมที่ประสานความร่วมมือกับเครือข่ายพันธมิตร (Supply Chain ในพื้นที่)', indicatorsYear:''},
        { number: '49', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ราย', 
        indicatorsName:'จำนวน Supply Chain ที่รับผิดชอบต่อสังคมและสิ่งแวดล้อมที่ได้รับการพัฒนาขีดความสามารถทางการตลาด', indicatorsYear:''},
        { number: '50', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'ราย', 
        indicatorsName:'จำนวน Supply Chain ที่รับผิดชอบต่อสังคมและสิ่งแวดล้อมที่ร่วมดำเนินงานกับ ททท.', indicatorsYear:''},
        { number: '51', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'หน่วยงาน', 
        indicatorsName:'จำนวนเจ้าของแหล่งท่องเที่ยว/ชุมชน/ผู้ประกอบการที่ได้รับการเพิ่มขีดความสามารถในการพัฒนาและเสนอขายสินค้าท่องเที่ยวมูลค่าเพิ่ม', indicatorsYear:''},
        { number: '52', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'แห่ง', 
        indicatorsName:'จำนวนชุมชน/แหล่งท่องเที่ยวที่ได้รับการพัฒนาขีดความสามารถในการเสนอขายและพัฒนาสินค้าสะท้อนวิถีไทยให้มีมูลค่าเพิ่ม', indicatorsYear:''},
        { number: '53', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'แห่ง', 
        indicatorsName:'จำนวนชุมชนท่องเที่ยวที่ได้รับการสร้างมูลค่าเพิ่ม', indicatorsYear:'กลยุทธ์ 3'},
        { number: '54', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'ผลรวมจำนวน', measure:'แห่ง', 
        indicatorsName:'จำนวนชุมชนท่องเที่ยว/แหล่งท่องเที่ยวที่ได้รับการยกระดับสู่ชุมชน Creative Tourism', indicatorsYear:''},

        { number: '', planName: 'ตลาดในประเทศ', type:'รายงานผลโดยตรง', calculating:'', measure:'', 
        indicatorsName:'', indicatorsYear:''},
    ];
    
    return (
        <>
            <div className='d-flex flex-column' style={{width: '100%'}}>
                <div className='search-wrapper-section d-flex flex-column'>
                    <div className="master-data2 d-flex flex-row p-2 justify-content-center">
                        <ReportTable data={data}/>
                        <div className="mr-20"></div>
                    </div>
                </div>
            </div>
        </>
    )
}