"use client"

import { ReactNode, useState } from "react";
import React from 'react';
import "../styles/scss/global.scss";
import { Inter } from "next/font/google";
// import { Providers } from "@components";
import { Provider } from "react-redux";
import Header from "@/components/Header";
import Sidebar from "@/components/Siderbar";
import {usePathname} from 'next/navigation';
import store from "@store";
import { MyContext } from "./MyContext";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "ททท",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: ReactNode }) {

  const [isClicked, setIsClicked] = useState(false);
  const [navId, setNavId] = useState(0);

  const handleButtonClick = () => {
    setIsClicked(!isClicked);
  };

  const changeNavHandle = (value: number) => {
    setNavId(value);
  };
  
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <Header />
          <div className={`d-flex content-body-wrapper${isClicked ? ' small-nav' : ''}`} style={{ marginTop: '20px' }}>
              {/* <Providers>{children}</Providers> */}
              <MyContext.Provider value={{navId, changeNavHandle}}>
                <Provider store={store}>{children}</Provider>
              </MyContext.Provider>
          </div>
        <Sidebar onButtonClick={handleButtonClick} navId={navId} />
      </body>
    </html>
  );
}


