export const sampleData = {
  operationFollowForm: {
    id: 1,
    tableDisplay: [
      {
        id: 1,
        idx: "2",
        status: "active",
        project_status: "request",
        project_year: "2565",
        project_seq: 3,
        project_name: 3,
        project_edit_status: "pending",
        project_edit_detail: "ตรวจสอบการทำงาน",
        department_name: "ททท",
      },
      {
        id: 2,
        idx: "2",
        status: "active",
        project_status: "request",
        project_year: "2565",
        project_seq: 3,
        project_name: 3,
        project_edit_status: "pending",
        project_edit_detail: "ตรวจสอบการทำงาน",
        department_name: "ททท",
      },
      {
        id: 3,
        idx: "2",
        status: "active",
        project_status: "request",
        project_year: "2565",
        project_seq: 3,
        project_name: 3,
        project_edit_status: "pending",
        project_edit_detail: "ตรวจสอบการทำงาน",
        department_name: "ททท",
      },
      {
        id: 4,
        idx: "2",
        status: "active",
        project_status: "request",
        project_year: "2565",
        project_seq: 3,
        project_name: 3,
        project_edit_status: "pending",
        project_edit_detail: "ตรวจสอบการทำงาน",
        department_name: "ททท",
      },
      {
        id: 5,
        idx: "2",
        status: "active",
        project_status: "request",
        project_year: "2565",
        project_seq: 3,
        project_name: 3,
        project_edit_status: "pending",
        project_edit_detail: "ตรวจสอบการทำงาน",
        department_name: "ททท",
      },
    ],
    section1: {
      yearBudget: "2566",
      budgetSource: "แหล่งงบประมาณ07",
      paymentList: "100000",
      organizationManageMent: "",
      act_group: "act1",
      strategic_goal: "1",
      strategic: "1",
      planning: "2",
      project_type: "3",
      project_name: "โครงการท่องเที่ยวเพื่อสุขภาพ",
    },
    section2: {
      budget: "70000000",
      quarter: {
        quarter1: {
          month1: "1000000",
          month2: "4000000",
          month3: "7000000",
          total: "5000000000",
          porportion: "20",
        },
        quarter2: {
          month1: "70000000",
          month2: "4000000",
          month3: "20000000",
          total: "70000000000",
          porportion: "65",
        },
        quarter3: {
          month1: "48000000",
          month2: "76000000",
          month3: "4600000",
          total: "7000000000",
          porportion: "20",
        },
        quarter4: {
          month1: "80000000",
          month2: "40000000",
          month3: "152000000",
          total: "8400000000",
          porportion: "60",
        },
      },
      suite_outside_policy: {
        isFlagship: true,
        isSla: true,
        isMainPlan: false,
        isPAIndicator: false,
        isClosedGap: false,
        isNone: false,
        isCsrProcess: true,
      },
      stakeHolder_Group: {
        isTatStaff: true,
        isCustomer: false,
        isGovernmentAudit: false,
        isSender: false,
        isProviderCustomer: true,
        isWorkingUnit: false,
        isFlagship: true,
      },
    },
    section3: {
      principal_reason: "ส่งเสริมการท่องเที่ยว",
      project_objective: {
        objective1: "ส่งเสริม sme",
        objective2: "gdp เติบโต",
        objective3: "ประเทศแขงแกร่ง",
        objective4: "เปิดจลาด",
      },
      list_operation_area: [
        {
          indx: "15",
          country_area: "ไทย",
          province: "โคราช",
        },
        {
          indx: "17",
          country_area: "ไทย",
          province: "ชลบุรี",
        },
      ],
      project_outcome: [
        {
          name_indicator: "ยอดขาย",
          total_percent: "7",
          quarter1_percent: "75",
          quarter2_percent: "20",
          quarter3_percent: "5",
          quarter4_percent: "41",
        },
      ],
      project_outcome_field: "1",
      project_target: [
        {
          indx: "4",
          target_name: "เด็ก",
        },
        {
          indx: "5",
          target_name: "ชาวต่างชาติ",
        },
      ],
    },
    section4: {
      project_start: "2023-06-19",
      project_end: "2023-09-27",
      flagship_risk: "ความเสี่ยงคน",
      risk_prevention: "ราชการ",
      benefit: "1",
    },
    section5: {
      return_roi: "100",
    },
    activitiesList: [
      {
        catname: "ทะเล",
        activity_type: "ชมวิว",
        activity_name: "ส่งเสริมการตลาด",
        activity_order: "1",
        activity_shared: "20",
        act_status: "",
        work_status: "",
        budget: "ในแผน",
        total_act_budget: "ในแผน",
      },
    ],
    activityForm: {
      budget: "ในแผน",
      catname: "ทะเล",
      activity_type: "ชมวิว",
      activity_order: "1",
      activity_name: "ส่งเสริมการตลาด",
      activity_description: "ชมวิวทะเล",
      activity_shared: "20",
      activity_shared_by_project: "4000000",
      activity_start: "2023-06-26",
      activity_end: "2023-06-30",
      project_outcome: [
        {
          name_indicator: "จำนวนคน",
          table_percent: 7,
          quarter1_percent: "5",
          quarter2_percent: "4",
          quarter3_percent: "20",
          quarter4_percent: "15",
        },
        {
          name_indicator: "ห้องพัก",
          table_percent: 7,
          quarter1_percent: "4",
          quarter2_percent: "25",
          quarter3_percent: "1",
          quarter4_percent: "76",
        },
      ],
      list_operation_area: [
        {
          indx: "1",
          country_area: "ไทย",
          province: "กทม",
        },
      ],
    },
  },
};
